export type Amenity = {
  id: string;
  label: string;
  iconName: string;
};

export type AmenityCategory = {
  id: string;
  label: string;
  iconName: string;
  items: Amenity[];
};

export const amenityCategories: AmenityCategory[] = [
  {
    id: "essentials",
    label: "Essentials",
    iconName: "Backpack",
    items: [
      { id: "essentials", label: "Essentials", iconName: "Sparkle" },
      { id: "bed_linens", label: "Bed linens", iconName: "Bed" },
      { id: "body_soap", label: "Body soap", iconName: "Drop" },
      { id: "shampoo", label: "Shampoo", iconName: "Drop" },
      { id: "conditioner", label: "Conditioner", iconName: "Drop" },
      { id: "shower_gel", label: "Shower gel", iconName: "Shower" },
      { id: "hot_water", label: "Hot water", iconName: "Thermometer" },
      { id: "heating", label: "Heating", iconName: "ThermometerHot" },
      { id: "air_conditioning", label: "Air conditioning", iconName: "Wind" },
      { id: "hangers", label: "Hangers", iconName: "CoatHanger" },
      { id: "iron", label: "Iron", iconName: "TShirt" },
      { id: "hair_dryer", label: "Hair dryer", iconName: "HairDryer" },
      { id: "extra_pillows_blankets", label: "Extra pillows and blankets", iconName: "Bed" },
      { id: "hot_water_kettle", label: "Hot water kettle", iconName: "CookingPot" },
    ],
  },
  {
    id: "kitchen_dining",
    label: "Kitchen and dining",
    iconName: "CookingPot",
    items: [
      { id: "kitchen", label: "Kitchen", iconName: "CookingPot" },
      { id: "kitchenette", label: "Kitchenette", iconName: "CookingPot" },
      { id: "refrigerator", label: "Refrigerator", iconName: "Cube" },
      { id: "mini_fridge", label: "Mini fridge", iconName: "Cube" },
      { id: "freezer", label: "Freezer", iconName: "Snowflake" },
      { id: "oven", label: "Oven", iconName: "Oven" },
      { id: "stove", label: "Stove", iconName: "Fire" },
      { id: "microwave", label: "Microwave", iconName: "Timer" },
      { id: "cooking_basics", label: "Cooking basics", iconName: "CookingPot" },
      { id: "dishes_silverware", label: "Dishes and silverware", iconName: "ForkKnife" },
      { id: "dishwasher", label: "Dishwasher", iconName: "Drop" },
      { id: "coffee_maker", label: "Coffee maker", iconName: "Coffee" },
      { id: "coffee", label: "Coffee", iconName: "Coffee" },
      { id: "blender", label: "Blender", iconName: "Blender" },
      { id: "toaster", label: "Toaster", iconName: "BreadSlice" },
      { id: "rice_maker", label: "Rice maker", iconName: "Bowl" },
      { id: "bread_maker", label: "Bread maker", iconName: "BreadSlice" },
      { id: "dining_table", label: "Dining table", iconName: "Table" },
      { id: "wine_glasses", label: "Wine glasses", iconName: "Wine" },
      { id: "trash_compactor", label: "Trash compactor", iconName: "Trash" },
      { id: "barbecue_utensils", label: "Barbecue utensils", iconName: "ForkKnife" },
      { id: "baking_sheet", label: "Baking sheet", iconName: "CookingPot" },
    ],
  },
  {
    id: "laundry_cleaning",
    label: "Laundry and cleaning",
    iconName: "TShirt",
    items: [
      { id: "washer", label: "Washer", iconName: "TShirt" },
      { id: "dryer", label: "Dryer", iconName: "Wind" },
      { id: "cleaning_products", label: "Cleaning products", iconName: "SprayBottle" },
      { id: "cleaning_during_stay", label: "Cleaning available during stay", iconName: "Broom" },
      { id: "drying_rack", label: "Drying rack for clothing", iconName: "CoatHanger" },
      { id: "clothing_storage", label: "Clothing storage", iconName: "Dresser" },
      { id: "laundromat_nearby", label: "Laundromat nearby", iconName: "MapPin" },
    ],
  },
  {
    id: "bedroom_bath",
    label: "Bedroom and bath",
    iconName: "Bed",
    items: [
      { id: "bathtub", label: "Bathtub", iconName: "Bathtub" },
      { id: "bidet", label: "Bidet", iconName: "Drop" },
      { id: "crib", label: "Crib", iconName: "Baby" },
      { id: "pack_n_play", label: "Pack 'n play / Travel crib", iconName: "Baby" },
      { id: "changing_table", label: "Changing table", iconName: "Baby" },
      { id: "room_darkening_shades", label: "Room-darkening shades", iconName: "Moon" },
      { id: "portable_fans", label: "Portable fans", iconName: "Fan" },
      { id: "safe", label: "Safe", iconName: "Lock" },
      { id: "mosquito_net", label: "Mosquito net", iconName: "Bug" },
    ],
  },
  {
    id: "entertainment",
    label: "Entertainment",
    iconName: "Television",
    items: [
      { id: "tv", label: "TV", iconName: "Television" },
      { id: "sound_system", label: "Sound system", iconName: "SpeakerHigh" },
      { id: "game_console", label: "Game console", iconName: "GameController" },
      { id: "record_player", label: "Record player", iconName: "Disc" },
      { id: "piano", label: "Piano", iconName: "MusicNote" },
      { id: "board_games", label: "Board games", iconName: "Dice" },
      { id: "books_reading", label: "Books and reading material", iconName: "Book" },
      { id: "arcade_games", label: "Arcade games", iconName: "GameController" },
      { id: "theme_room", label: "Theme room", iconName: "Star" },
      { id: "dedicated_workspace", label: "Dedicated workspace", iconName: "Desk" },
      { id: "ethernet", label: "Ethernet connection", iconName: "WifiHigh" },
    ],
  },
  {
    id: "family",
    label: "Family friendly",
    iconName: "UsersThree",
    items: [
      { id: "baby_bath", label: "Baby bath", iconName: "Baby" },
      { id: "baby_monitor", label: "Baby monitor", iconName: "Baby" },
      { id: "baby_safety_gates", label: "Baby safety gates", iconName: "ShieldCheck" },
      { id: "babysitter_recs", label: "Babysitter recommendations", iconName: "Phone" },
      { id: "children_books_toys", label: "Children's books and toys", iconName: "Puzzle" },
      { id: "children_dinnerware", label: "Children's dinnerware", iconName: "ForkKnife" },
      { id: "children_bikes", label: "Children's bikes", iconName: "Bicycle" },
      { id: "children_playroom", label: "Children's playroom", iconName: "Puzzle" },
      { id: "high_chair", label: "High chair", iconName: "Chair" },
      { id: "outlet_covers", label: "Outlet covers", iconName: "Plug" },
      { id: "table_corner_guards", label: "Table corner guards", iconName: "ShieldCheck" },
      { id: "window_guards", label: "Window guards", iconName: "ShieldCheck" },
    ],
  },
  {
    id: "outdoor",
    label: "Outdoor",
    iconName: "Tree",
    items: [
      { id: "backyard", label: "Backyard", iconName: "Tree" },
      { id: "patio_balcony", label: "Patio or balcony", iconName: "Sun" },
      { id: "outdoor_furniture", label: "Outdoor furniture", iconName: "Chair" },
      { id: "outdoor_dining", label: "Outdoor dining area", iconName: "ForkKnife" },
      { id: "outdoor_kitchen", label: "Outdoor kitchen", iconName: "CookingPot" },
      { id: "outdoor_shower", label: "Outdoor shower", iconName: "Shower" },
      { id: "outdoor_playground", label: "Outdoor playground", iconName: "Ladder" },
      { id: "bbq_grill", label: "BBQ grill", iconName: "Fire" },
      { id: "firepit", label: "Fire pit", iconName: "Campfire" },
      { id: "hammock", label: "Hammock", iconName: "Tree" },
      { id: "sun_loungers", label: "Sun loungers", iconName: "Sun" },
      { id: "pool", label: "Pool", iconName: "SwimmingPool" },
      { id: "hot_tub", label: "Hot tub", iconName: "Bathtub" },
      { id: "sauna", label: "Sauna", iconName: "ThermometerHot" },
      { id: "beach_access", label: "Beach access", iconName: "Waves" },
      { id: "lake_access", label: "Lake access", iconName: "Waves" },
      { id: "waterfront", label: "Waterfront", iconName: "Waves" },
      { id: "resort_access", label: "Resort access", iconName: "MapPin" },
      { id: "indoor_fireplace", label: "Indoor fireplace", iconName: "Fire" },
    ],
  },
  {
    id: "parking_transport",
    label: "Parking and transport",
    iconName: "Car",
    items: [
      { id: "free_parking", label: "Free parking on premises", iconName: "Car" },
      { id: "free_street_parking", label: "Free street parking", iconName: "Car" },
      { id: "paid_parking_on", label: "Paid parking on premises", iconName: "Car" },
      { id: "paid_parking_off", label: "Paid parking off premises", iconName: "Car" },
      { id: "ev_charger", label: "EV charger", iconName: "Lightning" },
      { id: "elevator", label: "Elevator", iconName: "ArrowsVertical" },
      { id: "private_entrance", label: "Private entrance", iconName: "Door" },
      { id: "luggage_dropoff", label: "Luggage dropoff allowed", iconName: "Suitcase" },
      { id: "bikes", label: "Bikes", iconName: "Bicycle" },
      { id: "kayak", label: "Kayak", iconName: "Boat" },
      { id: "boat_slip", label: "Boat slip", iconName: "Boat" },
    ],
  },
  {
    id: "safety",
    label: "Safety",
    iconName: "ShieldCheck",
    items: [
      { id: "smoke_alarm", label: "Smoke alarm", iconName: "Bell" },
      { id: "carbon_monoxide_alarm", label: "Carbon monoxide alarm", iconName: "Bell" },
      { id: "fire_extinguisher", label: "Fire extinguisher", iconName: "FireExtinguisher" },
      { id: "first_aid_kit", label: "First aid kit", iconName: "FirstAid" },
      { id: "fireplace_guards", label: "Fireplace guards", iconName: "ShieldCheck" },
      { id: "security_cameras", label: "Security cameras", iconName: "SecurityCamera" },
    ],
  },
  {
    id: "accessibility",
    label: "Accessibility and features",
    iconName: "Wheelchair",
    items: [
      { id: "single_level", label: "Single level home", iconName: "House" },
      { id: "wide_doorways", label: "Wide doorways", iconName: "Door" },
      { id: "private_living_room", label: "Private living room", iconName: "Armchair" },
      { id: "ceiling_fan", label: "Ceiling fan", iconName: "Fan" },
      { id: "climbing_wall", label: "Climbing wall", iconName: "Mountains" },
      { id: "pocket_wifi", label: "Pocket wifi", iconName: "WifiHigh" },
      { id: "wifi", label: "Wifi", iconName: "WifiHigh" },
      { id: "long_term_allowed", label: "Long-term stays allowed", iconName: "Calendar" },
      { id: "mini_golf", label: "Mini golf", iconName: "GolfHole" },
    ],
  },
  {
    id: "sports_recreation",
    label: "Sports and recreation",
    iconName: "Basketball",
    items: [
      { id: "gym", label: "Gym", iconName: "Barbell" },
      { id: "exercise_equipment", label: "Exercise equipment", iconName: "Barbell" },
      { id: "pool_table", label: "Pool table", iconName: "Circle" },
      { id: "ping_pong", label: "Ping pong table", iconName: "Circle" },
      { id: "bowling_alley", label: "Bowling alley", iconName: "Circle" },
      { id: "hockey_rink", label: "Hockey rink", iconName: "Circle" },
      { id: "ski_in_out", label: "Ski-in / Ski-out", iconName: "Mountains" },
      { id: "skate_ramp", label: "Skate ramp", iconName: "Lightning" },
      { id: "batting_cage", label: "Batting cage", iconName: "Baseball" },
      { id: "laser_tag", label: "Laser tag", iconName: "Crosshair" },
      { id: "life_size_games", label: "Life-size games", iconName: "Dice" },
    ],
  },
];

/** Flat list of all amenities for search */
export const allAmenities: Amenity[] = amenityCategories.flatMap(
  (cat) => cat.items,
);
