/**
 * Master cleaning checklist data — single source of truth for both
 * the /portal/cleaning-checklist page and the static PDF generated by
 * `scripts/build-checklist-pdf.tsx`.
 *
 * This is pure data (no JSX or React imports) so the build script can
 * import it from Node without a JSX transformer, and the page can
 * wrap each module with Phosphor icons separately.
 *
 * Content is enriched with the universal parts of the 19 S Edison
 * cleaning guide (specific counts, standards, and the high-touch
 * miss-list). Unit-specific content (addresses, door codes, phone
 * numbers, unit identifiers) is intentionally omitted — this file is
 * the portfolio-wide standard, not a property-specific guide.
 */

export type ChecklistItem = {
  id: string;
  text: string;
  /**
   * Human-readable condition. Undefined means "always applies
   * regardless of the property." Anything else is shown as a small
   * pill next to the item ("only if dishwasher", "only if pool") so
   * owners skip it when the home doesn't have that feature.
   */
  onlyIf?: string;
};

export type ChecklistModuleSlug =
  | "pre-clean"
  | "full-clean-misses"
  | "damaged-items"
  | "laundry"
  | "restock"
  | "interior"
  | "kitchen"
  | "bathrooms"
  | "bedrooms"
  | "living"
  | "entry"
  | "outdoor"
  | "photos"
  | "final";

export type ChecklistModule = {
  id: ChecklistModuleSlug;
  title: string;
  subtitle: string;
  items: ChecklistItem[];
};

export const MODULES: ChecklistModule[] = [
  {
    id: "pre-clean",
    title: "Before you start",
    subtitle: "Document the condition before touching anything.",
    items: [
      {
        id: "pre-photo-rooms",
        text: "Photograph every room before cleaning starts.",
      },
      {
        id: "pre-damage-log",
        text: "Log any damage or missing items in a note before moving things around.",
      },
      {
        id: "pre-lost-items",
        text: "Check under beds, couches, and nightstands for lost items.",
      },
      {
        id: "pre-trash",
        text: "Empty all interior and exterior trash bins.",
      },
      {
        id: "pre-windows",
        text: "Open windows for 10 minutes to air the home out.",
      },
      {
        id: "pre-before-after",
        text: "Take quick before and after photos for your own records. Helpful if anything gets flagged later.",
      },
    ],
  },
  {
    id: "full-clean-misses",
    title: "The spots people miss",
    subtitle: "Small details, huge difference in how the home feels.",
    items: [
      {
        id: "misses-baseboards",
        text: "Baseboards: check for dust and dirt buildup.",
      },
      {
        id: "misses-walls",
        text: "Walls, doors, and trim: wipe off scuff marks.",
      },
      {
        id: "misses-high-touch",
        text: "Light switches, door handles, and remotes. High-touch spots collect everything.",
      },
      {
        id: "misses-glass",
        text: "Mirrors, glass cups, windows, and glass tables: wipe streaks and fingerprints.",
      },
      {
        id: "misses-behind",
        text: "Behind doors, under furniture, and under beds: check for trash or dust.",
      },
      {
        id: "misses-sheets-hair",
        text: "Sheets: even one hair on a pillow makes a guest feel like the bed was not cleaned. Check carefully.",
      },
    ],
  },
  {
    id: "damaged-items",
    title: "Damaged or stained items",
    subtitle: "Photos first, then decide wash or replace.",
    items: [
      {
        id: "damage-photo",
        text: "Take photos of any damage before touching it. Send us a message in the portal if you want us to follow up.",
      },
      {
        id: "damage-wash-check",
        text: "If the item can be washed, check whether the stain came out. If it did, you're clear to move on.",
      },
      {
        id: "damage-broken",
        text: "If the item is broken or beyond use, document it with photos and send us a message. We often keep backups and can help replace it.",
      },
    ],
  },
  {
    id: "laundry",
    title: "Laundry",
    subtitle: "Towels first, then sheets. One load at a time.",
    items: [
      {
        id: "laundry-towels-first",
        text: "Start towels and bath mats first so they finish drying before sheets.",
      },
      {
        id: "laundry-sheets-second",
        text: "Start sheets after towels move to the dryer.",
      },
      {
        id: "laundry-check-stains",
        text: "Check every sheet, pillowcase, and towel for stains or damage before washing.",
      },
      {
        id: "laundry-washer-drum",
        text: "Wipe inside the washer drum after the last load.",
        onlyIf: "has washer",
      },
      {
        id: "laundry-dryer-lint",
        text: "Empty the dryer lint trap.",
        onlyIf: "has dryer",
      },
      {
        id: "laundry-fold-put-away",
        text: "Finish laundry all the way: dry, fold, put away. Leave nothing in the washer or dryer.",
      },
    ],
  },
  {
    id: "restock",
    title: "Restock supplies",
    subtitle:
      "Refill anything under 75%. Ideally everything at 100% before check-in.",
    items: [
      {
        id: "restock-shampoo",
        text: "Shampoo, conditioner, and body wash at 75%+ or replace. Preferably 100%.",
      },
      {
        id: "restock-kitchen-basics",
        text: "Coffee, tea, sugar, oil, salt, and pepper restocked to 100%.",
      },
      {
        id: "restock-coffee-pods",
        text: "Coffee pods restocked.",
        onlyIf: "has coffee maker",
      },
      {
        id: "restock-dish-soap",
        text: "Dish soap, dishwasher pods, and fresh sponges.",
      },
      {
        id: "restock-paper-towels",
        text: "Paper towels: 2 rolls total. One full roll on the counter, one half-used (or backup) under the sink.",
      },
      {
        id: "restock-trash-bags",
        text: "Leave a full roll of trash bags in both the kitchen and the bathroom.",
      },
    ],
  },
  {
    id: "interior",
    title: "Interior standards",
    subtitle: "Every room, every time.",
    items: [
      {
        id: "interior-surfaces",
        text: "Wipe all counters, tables, shelves, light switches, doorknobs, and handles with disinfectant.",
      },
      {
        id: "interior-vacuum",
        text: "Vacuum all carpets and rugs.",
      },
      {
        id: "interior-mop",
        text: "Sweep and mop kitchen, bathroom, and hard-floor areas.",
      },
      {
        id: "interior-lights",
        text: "Check every light bulb. Replace any that are dead or dim.",
      },
      {
        id: "interior-dust",
        text: "Dust picture frames, shelves, fans, and accessible vents.",
      },
      {
        id: "interior-trash-liners",
        text: "Fresh trash liners in every bin.",
      },
    ],
  },
  {
    id: "kitchen",
    title: "Kitchen and pantry",
    subtitle: "The room guests judge first.",
    items: [
      {
        id: "kitchen-fridge-clear",
        text: "Empty the fridge of any food left by guests. Wipe shelves and drawers.",
      },
      {
        id: "kitchen-fridge-freezer",
        text: "Check the freezer. Toss expired or opened items.",
      },
      {
        id: "kitchen-dishwasher-empty",
        text: "Run the dishwasher on an empty rinse cycle if any dishes were left.",
        onlyIf: "has dishwasher",
      },
      {
        id: "kitchen-sink-counter",
        text: "Scrub the sink, polish the faucet, wipe the backsplash.",
      },
      {
        id: "kitchen-microwave",
        text: "Wipe inside the microwave. Check for spills on the turntable.",
      },
      {
        id: "kitchen-oven-stovetop",
        text: "Wipe the stovetop and oven front. Deep clean if anything is burnt on.",
      },
      {
        id: "kitchen-coffee-maker",
        text: "Descale the coffee maker at least once a month.",
        onlyIf: "has coffee maker",
      },
    ],
  },
  {
    id: "bathrooms",
    title: "Bathrooms",
    subtitle: "Scrub, polish, restock. Specific counts matter.",
    items: [
      {
        id: "bath-sink",
        text: "Scrub the sink, polish the faucet and mirror.",
      },
      {
        id: "bath-tub-shower",
        text: "Scrub the tub, shower walls, and glass. Check the drain for hair.",
      },
      {
        id: "bath-caulk",
        text: "Wipe the caulk line along the tub and toilet base.",
      },
      {
        id: "bath-toilet",
        text: "Clean the toilet bowl, base, and seat.",
      },
      {
        id: "bath-toilet-paper",
        text: "Toilet paper: 6 rolls total per bathroom. 1 on the holder, 5 backup.",
      },
      {
        id: "bath-towels-hung",
        text: "Bath towels: 8 total (2 per guest). Fold and hang with a fan fold, as shown in the listing photos.",
      },
    ],
  },
  {
    id: "bedrooms",
    title: "Bedrooms",
    subtitle: "Fresh linens, neat beds, nothing left behind.",
    items: [
      {
        id: "bed-fresh-linens",
        text: "Make every bed with fresh sheets and pillowcases.",
      },
      {
        id: "bed-pillows-king-queen",
        text: "4 pillows on each King or Queen bed.",
      },
      {
        id: "bed-pillows-twin",
        text: "2 pillows on each Twin bed.",
      },
      {
        id: "bed-extra-sheets",
        text: "Leave 1 extra sheet set per bed in the bedroom closet.",
      },
      {
        id: "bed-arrange-pillows",
        text: "Arrange decorative pillows and throws to match the listing photos.",
      },
      {
        id: "bed-nightstands",
        text: "Check nightstand drawers for guest belongings. Wipe the top.",
      },
      {
        id: "bed-under",
        text: "Vacuum or sweep under the bed and in the corners.",
      },
      {
        id: "bed-closet",
        text: "Open every closet. Count the hangers. Leave them evenly spaced.",
      },
    ],
  },
  {
    id: "living",
    title: "Living room and dining",
    subtitle: "The space guests spend the most time in.",
    items: [
      {
        id: "living-cushions",
        text: "Fluff and rotate couch cushions. Check underneath for crumbs and items.",
      },
      {
        id: "living-decor",
        text: "Wipe tables, shelves, remotes, and décor.",
      },
      {
        id: "living-blinds",
        text: "Adjust blinds or shades to match the standard look.",
      },
      {
        id: "living-tv",
        text: "Power the TV on. Check for cracks. Confirm Roku or Apple TV is signed in.",
        onlyIf: "has tv",
      },
      {
        id: "living-fireplace",
        text: "Sweep the fireplace hearth. Check the glass.",
        onlyIf: "has indoor fireplace",
      },
    ],
  },
  {
    id: "entry",
    title: "Entry, lobby, and hallways",
    subtitle: "First impressions when guests arrive.",
    items: [
      {
        id: "entry-tables",
        text: "Wipe entry tables, mirrors, and handles.",
      },
      {
        id: "entry-scuffs",
        text: "Check for scuffs or marks on walls and doors. Wipe any you can.",
      },
      {
        id: "entry-sweep",
        text: "Sweep and vacuum the lobby, inside the front door, and the area in front of the apartment.",
      },
      {
        id: "entry-welcome",
        text: "Ensure welcome items (snacks, note card, key instructions) are in place.",
      },
    ],
  },
  {
    id: "outdoor",
    title: "Exterior, patio, and balcony",
    subtitle: "Sweep, wipe, and check anything outside.",
    items: [
      {
        id: "outdoor-sweep",
        text: "Sweep the porch, balcony, or patio. Remove trash, leaves, and cobwebs.",
        onlyIf: "has patio or balcony",
      },
      {
        id: "outdoor-furniture-covers",
        text: "Check outdoor furniture covers. Remove and wash if dirty.",
        onlyIf: "has outdoor furniture",
      },
      {
        id: "outdoor-furniture-wipe",
        text: "Wipe outdoor furniture. Check cushions for rain or stains.",
        onlyIf: "has patio or balcony",
      },
      {
        id: "outdoor-bbq",
        text: "Scrub BBQ grates and wipe the outside of the grill.",
        onlyIf: "has BBQ grill",
      },
      {
        id: "outdoor-pool",
        text: "Test pool chemistry. Record pH and chlorine levels.",
        onlyIf: "has pool",
      },
      {
        id: "outdoor-hot-tub",
        text: "Check hot tub cover and water level. Skim any debris.",
        onlyIf: "has hot tub",
      },
      {
        id: "outdoor-trash-bins",
        text: "Take all trash and recycling bags to the outside bins. Roll bins to the curb on your neighborhood's pickup day.",
      },
      {
        id: "outdoor-lights",
        text: "Check all exterior lights. Switch on/off to verify.",
      },
    ],
  },
  {
    id: "photos",
    title: "Finished photos",
    subtitle:
      "A visual record for your own files. Any order is fine. Optional but recommended.",
    items: [
      { id: "photo-entry", text: "Entry area." },
      { id: "photo-kitchen", text: "Kitchen (include cabinets and drawers)." },
      { id: "photo-dining", text: "Dining area." },
      { id: "photo-living", text: "Living room." },
      { id: "photo-bathrooms", text: "Every bathroom." },
      {
        id: "photo-bedrooms",
        text: "Every bedroom, including under the beds.",
      },
      { id: "photo-laundry", text: "Laundry room." },
      { id: "photo-front", text: "Front patio or lobby." },
      {
        id: "photo-balcony",
        text: "Balcony or back patio.",
        onlyIf: "has patio or balcony",
      },
      {
        id: "photo-trash",
        text: "Outdoor trash and recycling bins in place.",
      },
      {
        id: "photo-supply-closet",
        text: "Supply closet. Useful for knowing what to reorder.",
      },
      {
        id: "photo-front-door",
        text: "Locked front door (proof the home is secured).",
      },
      {
        id: "photo-tv-off",
        text: "TV powered off with no cracks on screen.",
        onlyIf: "has tv",
      },
    ],
  },
  {
    id: "final",
    title: "Final walkthrough",
    subtitle: "One last pass before you lock up.",
    items: [
      {
        id: "final-rooms-missed",
        text: "Walk every room one more time. Check that nothing was missed.",
      },
      {
        id: "final-surfaces",
        text: "Confirm all surfaces, floors, and beds are clean.",
      },
      {
        id: "final-laundry-done",
        text: "Laundry is fully done: dry, folded, and put away.",
      },
      {
        id: "final-thermostat",
        text: "Set the thermostat to 70°F.",
      },
      {
        id: "final-tv-off",
        text: "Make sure TVs are off. No cracks or broken displays.",
      },
      {
        id: "final-remotes",
        text: "Confirm all remotes, smoke detectors, and devices have working batteries.",
      },
      {
        id: "final-snacks",
        text: "Place snacks on the kitchen counter or entry table.",
      },
      {
        id: "final-lights-locks",
        text: "Lights off, windows closed, all doors locked.",
      },
      {
        id: "final-reorder",
        text: "Jot down anything running low so you can reorder it before the next stay.",
      },
    ],
  },
];

export const TOTAL_ITEMS = MODULES.reduce((sum, m) => sum + m.items.length, 0);
